import { Request } from './controllers';
import * as storage from './apis/storage.util';
export * from './controllers';
export { Operator } from './modules/filterConfiguration';
export declare const searchStore: <T>(request: Request<T>) => [Promise<any>, () => void];
export declare const createStore: (storeName: string) => (indexConfig: storage.SimplifiedIndexConfig) => (keyPath: string) => Promise<void>;
export declare const addDocumentsToStore: <T>(storeName: string) => (data: T[]) => Promise<void>;
export declare const getAllValuesOfProperty: <T extends IDBValidKey>(storeName: string) => (propertyName: string) => Promise<T[]>;
export declare const getNumberOfDocumentsInStore: (storeName: string) => Promise<number>;
export declare const getDocuments: <T>(storeName: string) => (documentIds: IDBValidKey[]) => Promise<T[]>;
export declare const deleteStore: (storeName: string) => Promise<void>;
export declare const deleteStoreIfExist: (storeName: string) => Promise<void>;
export declare const deleteAllStores: () => Promise<void>;
export declare const doesStoreExist: (storeName: string) => Promise<boolean>;
