name: 'Browser Search build'
description: 'checks, tests, builds'
inputs:
  package:  # id of input
    description: 'package to build'
    required: true

runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        shell: bash
        working-directory: packages/${{ inputs.package }}

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            packages/${{ inputs.package }}/node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ inputs.package }}
          restore-keys: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ inputs.package }}

      - name: Install dependencies
        run: |
          if ${{ steps.yarn-cache.outputs.cache-hit }} = 'true'
          then
            echo "Cache hit - skipping dependency installation"
          else
            yarn install --frozen-lockfile
          fi
        shell: bash
        working-directory: packages/${{ inputs.package }}

      - name: test
        run: yarn run test
        shell: bash
        working-directory: packages/${{ inputs.package }}

      - name: Build
        run: yarn run build
        shell: bash
        working-directory: packages/${{ inputs.package }}
