import { Chance } from 'chance';
import { times } from 'ramda';

import { Person } from './person';

export const generatePerson = (): Person => (
  {
    id: chance.guid(),
    name: chance.name(),
    age: chance.age(),
    email: chance.email(),
    salary: chance.natural({ min: 20000, max: 100000 }),
    profession: chance.profession(),
    hobbies: chance.pickset(hobbiesSet, chance.natural({ min: 0, max: 4 })),
    country: chance.pickone(countrySet),
  }
)

export const generatePersons = (n: number) => times(generatePerson, n);

const chance = new Chance();

const countrySet = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kenya",
  "Laos",
  "Latvia",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Malta",
  "Mexico",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Senegal",
  "Singapore",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Venezuela",
  "Vietnam",
];

const hobbiesSet = [
  "Football",
  "Swimming",
  "Singing",
  "Painting",
  "Writing",
  "Reading",
  "Hiking",
  "Cycling",
  "Trekking",
  "Basketball",
  "Tennis",
  "Guitar",
  "Movies",
  "Netflix",
  "Skiing",
  "Running"
];