name: 'Browser Search E2E'
description: 'E2E'

runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
      working-directory: packages/e2e

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          packages/e2e/node_modules
        key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-e2e
        restore-keys: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-yarn-e2e

    - name: Install e2e dependencies
      run: |
        if ${{ steps.yarn-cache.outputs.cache-hit }} = 'true'
        then
          echo "Cache hit - skipping dependency installation"
        else
          yarn install --frozen-lockfile
        fi
      shell: bash
      working-directory: packages/e2e

    - name: builds
      uses: ./.github/actions/build

    - name: Run E2E tests
      run: yarn run test
      shell: bash
      working-directory: packages/e2e
