name: tests - builds - release

on: [push]

env:
  NODE_VERSION: 16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: test
        uses: ./.github/actions/test

  # e2e:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: e2e
  #       uses: ./.github/actions/e2e

  # publish:
  #   needs: [test, e2e]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: release
  #       uses: ./.github/actions/release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        